

# Introduction to Python Week 2 SOLUTIONS:
# Arrays, and Loops
### Written by Jackie Champagne; adapted by Hannah Hasson, Mary McMullan, and Kassie Moczulski

Reminder: [Code of conduct](https://docs.google.com/presentation/d/1UiBbQLGCZ_8VTTufJGitjnfz2Lj12TzAPuvHLvRLMhk/edit?usp=sharing)



---


&nbsp;

Welcome back! Hopefully now you should be comfortable with some basic Python syntax. Let's get into something a bit more interesting today: how to store large amounts of data and how to sort through that data!


Today we will go over arrays, for loops, and dive deeper into functions.


# **1-dimensional lists and arrays**

When working with data, you usually won't be dealing with just one number, but a collection of values. These collections can consist of floats, integers, strings, or a combination of them. We distinguish here two types of data structures: lists and arrays.

**Lists** are typically denoted by brackets [...], where you can fill in the list with information. A simple way of visualizing it is with a row in an excel spread sheet. There are multiple boxes, with each box holding one piece of information.

The following is an example of a 1D list:

In [1]:
beemovie = ['Barry B. Benson', 'Vanessa Bloome', 'Ray Liotta as Ray Liotta', 'Partick Warburton as Ken']
print(beemovie)

['Barry B. Benson', 'Vanessa Bloome', 'Ray Liotta as Ray Liotta', 'Partick Warburton as Ken']


##**Indexing**
To access the data within the list you use indexing. An index is the position of some element in an array. To do this you would use the index of the column and row to get the value.

###Note that **Python uses zero-based indexing!!**

This means that the first value of a list is the 0th index. Repeating that: **the first value in a list is the zeroth index**. So the second element has index 1, the third has index 2, and so on...

<p align="center">
  <img width="350" src="https://www.thecrazyprogrammer.com/wp-content/uploads/2015/05/Array-in-Java.gif">
</p>

&nbsp;

To call a certain value from a list, call the list name followed by brackets containing the index of the value you want:

    beemovie[index]

Here is a quick example:

In [3]:
print(beemovie[0])

Barry B. Benson


The index has to be an **integer**, you cannot have the 1.5th element in an array. But not only can you count forward with index number, you can also count backward! For example `beemovie[-1]` would give you the last entry in the array, and `beemovie[-2]` would be the second to last entry.


In [ ]:
print(beemovie[-1])

Take a look below at what happens when we try to access an index in the array that we didn't define. This is a common coding error typically called an "Out of Bounds Exception".

In [ ]:
print(beemovie[97])

&nbsp;
##**Slicing arrays and lists**

You can also grab **slices** of lists between certain index values. This is helpful if you want to plot only a small subsample of your data, for example.

&nbsp;

For slicing, use a colon inside where you are calling the range of indicies you'd like to return. Syntax:

    :x - from beginning to index x
    x: - from index x until the end
    a:b - from index a to b
    a:b:c - every c'th entry between indices a and b
    
These can be combined, e.g. a::c goes from index a until the end in steps of c.

&nbsp;

Slicing is *exclusive*, so the last index of a range isn't included. For example, if you want to take index two through six of a list you should do:

    list[2:7]


Take a second to use the code below to test out how slicing works.

In [8]:
test_list = [42,67,21,33,90,26]   # A list with 6 elements.
print('1st four elements:',test_list[:4])

print('Test out slices below!')
### Try out different slices below ####

print(test_list[2:6:2])

1st four elements: [42, 67, 21, 33]
Test out slices below!
[21, 90]




## Question 1: Using the list defined below called `nums`, use the slicing feature inside a single print statement to display only even values from 4 to 12.

In [10]:
nums = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] # don't change this line!

# solution here

print(nums[3:13:2])


[4, 6, 8, 10, 12]


##**Numpy arrays**

While working with lists is incredibly useful, there are some interesting properties that can become a problem. For example if you want to do a mathematical operation on a list, it doesn't work quite as easy as we expect.

For example, the following cell:

In [11]:
teehee = [1.0, 2.0, 3.0, 4.0, 5.0]
teehee5 = 5 * teehee

print(teehee5)

[1.0, 2.0, 3.0, 4.0, 5.0, 1.0, 2.0, 3.0, 4.0, 5.0, 1.0, 2.0, 3.0, 4.0, 5.0, 1.0, 2.0, 3.0, 4.0, 5.0, 1.0, 2.0, 3.0, 4.0, 5.0]


This won't  multiply all the values within the list by 5, but instead will repeat the original list 5 times. This clearly is a problem when working with data, which we often must manipulate and do math with!

</br>

To get around this issue we can create **arrays** from our lists using the `array()` command from the `numpy` package. **Arrays are able to store data like lists AND do math with it!**

</br>

We start off by importing the `numpy` library and renaming it as `np` (so we don't have to type as much). Next we make 2 lists of numbers and try adding them. Then we convert these lists to arrays using `np.array(my_list)` for each and add the arrays together.

In [12]:
import numpy as np

#make a couple of lists
a = [0 , 1 , 2 , 3]
b = [4 , 5 , 6 , 7]

print(a + b)

[0, 1, 2, 3, 4, 5, 6, 7]


In [13]:
#convert lists into numpy arrays!
a1 = np.array(a)
b1 = np.array(b)

print(a1 + b1)

[ 4  6  8 10]


In [14]:
np.array(2,3,4,5,6)

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [15]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

As you can see, using the `numpy` library adds the corresponding elements in the array together instead of simply printing the two added lists next to each other.

You can use all the basic math operations on arrays, and they will always apply to each element. For example, multiplying all the elements in an array by 7 is this easy:

In [16]:
c = 7 * a #multipling a list

print(c)

[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]


In [17]:
c1 = 7 * a1 #multiplying an array

print(c1)

[ 0  7 14 21]


As a gentle reminder, here are what all the basic math operations look like again:


    +           add
    -           subtract
    *           multiply
    /           divide
    **          power
    np.log()    log-base e (natural log)
    np.log10()  log-base 10
    np.exp()    exponential


All of these would apply the operation to each element of the array, including numpy functions like `np.log`, `np.sin`, etc...

This shows another example of how numpy can make scientific use of Python simpler and more convenient.

###**Functions that makes arrays for you: `linspace` and `arange`**

The first is [`np.linspace()`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) and the second is [`np.arange()`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html). Both give you an array with numbers between two values that are linearly spaced (e.g. 2, 4, 6, 8, 10), but they do it slightly differently.


&nbsp;
    
The syntax is the following:

    np.linspace(beginning_number, end_number, number_of_points)
    np.arange(beginning_number, end_number, step_size)

The `step_size` here corresponds to the difference between one point and the next in your array of values.

&nbsp;

Typically `np.linspace` is used when you know how many datapoints you need, and `np.arange` is used when you want to jump by a certain amount between each number. The latter is typically only used for stepping by whole numbers, but you can still use it with decimals.
  
&nbsp;

An important note is that `np.linspace` is an *inclusive* function, meaning that the end number you give is included in the output array. However, `np.arange` is *exclusive*, meaning the end number is not included. Keep this in mind as we move forward!


In [18]:
a = np.linspace(0,4,5) #Makes an array which has 5 entries and goes from 0 to 4. Notice the data type of the elements!

print(a)

[0. 1. 2. 3. 4.]


There are TONS of functions that will create arrays for you following some rule/pattern, check out this documentation later to look at them: https://numpy.org/doc/2.1/reference/routines.array-creation.html

<br>

**Now let's combine our knowledge of arrays with our knowledge of if statements from last time!**

Like we mentioned earlier, the syntax of arrays and indices can all be combined.


###Question 2: Create two `numpy` arrays that have 5 entries, one that is even and one that is odd. Now divide one by the other and print the result.

In [32]:
#solution here

a = np.linspace(2,10,5)
b = np.linspace(1,9,5)

c = np.arange(2,11,2)
d = np.arange(1,11,2)

print(a)
print(b)
print(a/b)

print(c)
print(d)
print(c/d)


[ 2.  4.  6.  8. 10.]
[1. 3. 5. 7. 9.]
[2.         1.33333333 1.2        1.14285714 1.11111111]
[ 2  4  6  8 10]
[1 3 5 7 9]
[2.         1.33333333 1.2        1.14285714 1.11111111]


### Question 3: Create a linear array (using `np.linspace`) with 10 values between 0 and 1.  Write an `if` statement that checks whether the last entry in the array is less than one. If so, have it print out the last entry. If not, have it print out "[last entry] is not less than one."


In [22]:
# solution here

x = np.linspace(0,1,10)

print(x)

if x[-1] < 1:
  print(x[-1])
else:
  print(x[-1], 'is not less than one.')

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
1.0 is not less than one.


### Question 4: Create a `linspace` array with ten entries between 1 and 100. Create an `arange` array from 100 to 200 (with 200 included!) spaced by 10s. Print them to check 😀

In [25]:
# solution here

y = np.linspace(1,100,10)
print(y)

z = np.arange(100,201,10)
print(z)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
[100 110 120 130 140 150 160 170 180 190 200]


#**Loops**

Loops give us the ability to repeat a simple set of commands many times in a row. There are a few types of loops .

## **For Loops**

The first is the **for loop**. The **for loop** is most commonly used when performing an operation over each element, or specfic elements, in an array/list.


The **for loop** goes over every entry in a list, doing something at each pass.

The basic syntax of using an array in a for loop is the following:


```
x = [value1, value2, value3, ...]    #this can be a list or an array

for i in x:
  do something
```

`x` is our array or list that we are looping through. Remember that these are variable names, where `x` is either generated by a function or was previously defined in our code. The first variable, `i`, holds one element in the list at a time as we loop through. We can change `i` to be called whatever we'd like.

<br>

Further, exactly like our if statements from last week, *indentation matters here!* You **must** indent the line after the `for ### in ###:` line.


A for loop can be used to print out all the values in an array:

In [33]:
shrek = ['Shrek', 'Donkey', 'Fiona', 'Lord Farquaad']

for name in shrek:
  print(name) # name is the element in our list 'shrek'. The for loop automatically goes through each element in order!

Shrek
Donkey
Fiona
Lord Farquaad


But you can also use it to print all the numbers from 0 to 10 by using the `range` function.


`range(input_value)` will generate a list of numbers, starting from zero and incrementing by 1 until it reaches the input value (but it doesn't include that value). Combining `range` with the `len` function (which prints the length of a list or array) can produce a full list of the indices in an array. This becomes **extremely useful** when one might want to access the array by its index numbers, rather than its actual elements. See the difference below, compared to our for loop in the code block above!

In [34]:
counter = 0
for i in range(11): #this just outputs numbers 0-10
  print(i)
  counter += 1

print('counter:', counter)

0
1
2
3
4
5
6
7
8
9
10
counter: 11


In [36]:
for i in range(len(shrek)): # Notice how this loop returns the same result as our previous code block (for name in shrek:)
  print('index:', i)
  print('element:', shrek[i], '\n') # 'i' is the index value here, and shrek[i] is the element at that index!

print('\n The loop is over!')

index: 0
element: Shrek 

index: 1
element: Donkey 

index: 2
element: Fiona 

index: 3
element: Lord Farquaad 


 The loop is over!


The `range()` function can also be altered to start at a specific value, and to increment by a specific value. `range(4,10)` will generate values starting at 4, and incrementing by 1, up to 10 (but does NOT include 10!).

`range(4,14,2)` will increment each value by 2. Check out the code below to see what this would look like! Try changing the values and seeing what the loop includes and doesn't include!

In [ ]:
for x in range(4,14,2):
  print(x)

##**While loops**
But the for loop isn't the only loop at our disposal. We can also use a while loop, which keeps going until it satisfies a condition.

The syntax for the while loop is:


```
while (condition is true):
  do something
```

**It is important to always make sure your loop will reach an end**, otherwise it will go on forever!!! To track the condition, you will make some **index variable** that will change each time according to a statement in the loop. Programmers often use `i` as the name of the index variable:

In [ ]:
i = 0 # We used i in the earlier code block, so we give it a new value now.

while (i < 10):
  print(i)
  i = i + 2 # This increments the variable i by 2. Without this line, we would have an infinite loop!

&nbsp;

### Question 5a: Here's an array below, called `bikinibottom`. Write a for loop that prints out `"Barnacles, [name]!"` for each element of the list individually. (Tip: to stick a string next to a variable in a print statement, separate them with a comma). Use the syntax `for x in bikinibottom`.


In [43]:
bikinibottom = np.array(['Gary', 'Spongebob','Patrick', 'Squidward', 'Sandy'])

# solution here

for x in bikinibottom:
  print('Barnacles,', x,'!')

Barnacles, Gary !
Barnacles, Spongebob !
Barnacles, Patrick !
Barnacles, Squidward !
Barnacles, Sandy !


###Question 5b: Do the same but use a while loop. Start with our index at 0 and add 1 each pass through the loop until i is equal to the length of bikinibottom. Print the element of bikinibottom at index i in each step of the loop. HINT: Be careful about what order you put the increment of the index i in.

In [46]:
#solution here
i = 0
while (i<(len(bikinibottom))):
  print('Barnacles,', bikinibottom[i],'!')
  i += 1

Barnacles, Gary !
Barnacles, Spongebob !
Barnacles, Patrick !
Barnacles, Squidward !
Barnacles, Sandy !


# &nbsp;
&nbsp;
-------
#PAUSE HERE AND TAKE A BREAK!
-------

#**Combining loops and logic**

But what if you want to go through some data (an array), and if a condition is fulfilled you stop the loop- but you don't know if or when the condition will be fulfilled?

That brings us to combining the two powerful tools of code that we have learned so far: **if statements** and **loops**. More specificially, if statments nested **inside** of loops! This means that a condition is checked every time the loop repeats. Be extra careful about indentation here!



```
for x in data:
  if condition_is_met:
    do something # ONLY when condition is met
```


See the example below for a loop that only prints the odd numbers in an array:

In [ ]:
x = range(1,11)


for i in x:
  if (i % 2) != 0: # This condition uses the modulo operator %, which gives the remainder of division.
    print(i)

Now how do we stop a loop before it executes every data point? We can use the `break` function. This will break out of the current loop it is running through and **can make it easier than working with a while loop**. An example is:

In [ ]:
for i in range(len(shrek)):
  if (shrek[i] == 'Fiona'):
    print("Fiona is located at index", i)
    break

&nbsp;

Combo time! You now know we can embed if statements into for loops, which checks the conditional statement for every value of the array.




## **Nested For Loops**

Before we dive into 2-D arrays, let's give a brief introduction to **nested for loops.** Think of this as a loop within a loop.

If we have two 1-D arrays (or lists) and we want to loop through one array during each step of looping through the other array, we would do the following:

In [ ]:
odd_numbers = range(1,6,2) #make a list of odd numbers 1,3,5

for name in shrek:
  # We can add code here if we'd like- it gets executed each time we loop through the 'shrek' array! Try it out :)
  for value in odd_numbers:
    print(name, value)

***Be extra careful about indentation here!***

When might this be useful, you might ask? You will see as we introduce the mighty 2-D arrays!

### Question 6
### a) Use `np.array` to create an array containing the values [0.5, 2, 3, 7].

### b) Then make a `for` loop that goes through each element of the array and adds two.

### c) After adding 2, use `if` and `elif` inside the `for` loop to check if the value is now less than 5, equal to 5, or greater than 5. If a condition is satisfied, have it print that (e.g. '4 < 5').

In [51]:
#solution here

a = np.array([0.5, 2, 3, 7])

for x in a:
  x += 2
  if x < 5:
    print(x,'< 5')
  elif x == 5:
    print(x,'= 5')
  else:
    print(x,'> 5')

2.5 < 5
4.0 < 5
5.0 = 5
9.0 > 5


## 2-D arrays (and more)##
Your data might not be a 1-D list of numbers or letters. Instead it may sometimes look like an excel spreadsheet, with rows and columns. This is a 2-D array, what we typically use for storing data.

In [ ]:
hello = np.array([["who", "what", "when"],
                  ["where", "why", "how"]])



To index a specific element in a 2D array, you would give the row and column indices like a set of coordinates:

    arrayname[0,0] # again in row, col notation
    
Refer to this helpful diagram below that visually shows each index of a 2-D array.

<p align="center">
  <img width="350" src="https://iq.opengenus.org/content/images/2020/04/index.png">
</p>

Again, each index can be given as a variable, so long as the variable is an **integer**. You can't have the 1.5th element of a list.

Here is an example of how to index the same element in 3 different ways:

In [ ]:
hello[1]

In [ ]:
print(hello[1,2]) #get the element in the 2nd row & 3rd column
print(hello[1][2]) #This is another way to get the same value with different syntax

i = 1
j = 2
print(hello[i,j]) #A third way to get the same value, but this time using variables as the indexing value

You can also do similar slicing work with the 2-D arrays.

In [ ]:
#example lists
a = [0, 1, 2, 3]
b = [4, 5, 6, 7]
c = [8, 9, 10, 11]
d = [12, 13, 14, 15]

#a 2D array made of these lists
e = np.array([a, b, c, d])
print(e)

In [ ]:
print(e[2:4]) #print rows 3 and 4

In [ ]:
print(e[2][0:3]) #print row 3, the first 3 elements

Now to loop over an array you need not just one loop but two, since there's a row index AND a column index. We have returned to nested loops!

The first loop goes through and when i = 1, we are looking at the b array from above (since it is the second entry). Then when going through the second loop, and j = 3 for example it will be the 4th entry (in this case a 7).


In [ ]:
len(e)

In [ ]:
np.shape(e)

In [ ]:
for i in range(len(e)): #loop through all rows
  for j in range(len(e[i])): #for each row, loop through all columns in that row
    print(e[i,j])

###Question 7: Looping through a 2D array
a) Make a 2D array of numbers that is 4 rows and 4 columns.

b) Make a nested for loop that goes first through each row and prints the row number, then prints the element at each column in that row.

In [65]:
# Code your answer in here
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
c = [9, 10, 11, 12]
d = [13, 14, 15, 16]

M = np.array([a, b, c, d])

print(M)
print(range(len(M)))

for x in range(len(M)):
  print('row: ', x)
  for y in range(len(M[x])):
    print('element: ', M[x][y])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
range(0, 4)
row:  0
element:  1
element:  2
element:  3
element:  4
row:  1
element:  5
element:  6
element:  7
element:  8
row:  2
element:  9
element:  10
element:  11
element:  12
row:  3
element:  13
element:  14
element:  15
element:  16


&nbsp;

# **Array Manipulation and Attributes**
Before we end for today, lets cover how to change an array once it's been created, as well as another useful way to get an array's properties.

&nbsp;

##**Manipulating existing arrays**

You can **add values to the end of an array** using np.append(). Use it like this:

    new_array = np.append(array, something_appended)
    
You can even append another array, like this:

    array_appended = np.append(array, [5, 6])
    two_arrays_appended_together = np.append(array1, array2)

Here is an example:

In [ ]:
friends = np.array([4,5,6])
enemies = np.array([7,8,9])
everyone = np.append(friends,enemies)
print(everyone)

The last part of today will be some useful functions in the numpy library. You call these by `np.command(nameofarray)`:

    sum - sum all the elements in the array
    min - print minimum value in array
    max - print maximum value
    sort - print array in ascending order
    len - print number of elements along the row axis
    delete - remove the specified index of an array
    unique - returns the unique values in an array
    dot - matrix multiplication
    concatenate - joins arrays along an axis
    flatten - returns a copy of a 2-D or N-D array collapsed into one dimension


    

In [ ]:
new_array = np.delete(np.array(shrek),0)
print(new_array)

##**Array Attributes**

The above functions require the use of `np.command(array)`. Some functions for numpy arrays do not need the `np.` prefix, and rather can just be called like `array_name.command`:

```
ndim - returns the array dimensions (axes)
shape - returns the shape of an array (like 2x2, 4x5)
size - returns the total number of elements in an array
dtype - returns the data type of the array components
```



In [ ]:
np.shape(e)

If you'd like to know more about any of these commands or other functions not listed here (there are LOTS of numpy commands!) check out the documentation [here](https://numpy.org/doc/stable/index.html).

###Don't forget to do the exercises in the Exercises.ipynb file for Week 2! Collaboration with your peers is encouraged :)

Please stay after for a few minutes if you want to make plans with other students to work on the optional homework.

Finally, consider taking a moment to fill out the feedback [form](https://docs.google.com/forms/d/e/1FAIpQLSdzzC9-vBv5DflUQ2kgp4Z_6JKkvi_Id2D3lTLezRikHDJkww/viewform?usp=header) about this lesson.